cmake_minimum_required(VERSION 3.0)
project(RES LANGUAGES CXX)

set(CMAKE_CXX_STANDARD 98)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -D_M_IX86 -D_CRT_SECURE_NO_WARNINGS")

file(GLOB RES_SOURCE "*.cpp")
file(GLOB RES_HEADERS "*.h")

add_library(${PROJECT_NAME} STATIC ${RES_SOURCE} ${RES_HEADERS})
