cmake_minimum_required(VERSION 3.0)
project(GAME LANGUAGES CXX)


# стандарт
set(CMAKE_CXX_STANDARD 98)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -D_M_IX86")

# пути для include: gta2/, gta2/Engine, gta2/Game (global.h и кросс-инклюды)
include_directories(${CMAKE_CURRENT_LIST_DIR} ${CMAKE_CURRENT_LIST_DIR}/.. ${CMAKE_CURRENT_LIST_DIR}/../Engine)

# все поддиректории (классы) сборки Game
add_subdirectory(AIController)
add_subdirectory(Ambulance)
add_subdirectory(AmbulanceInfo)
add_subdirectory(ArrowTrace)
add_subdirectory(BrakeInfo)
add_subdirectory(Camera)
add_subdirectory(CameraOrPhysics)
add_subdirectory(Car)
add_subdirectory(CarDoor)
add_subdirectory(CarEngines)
add_subdirectory(CarGenerator)
add_subdirectory(CarModel)
add_subdirectory(CarPair)
add_subdirectory(CarSystemManager)
add_subdirectory(CarsPrefabs)
add_subdirectory(Character)
add_subdirectory(Checkpoint)
add_subdirectory(Collide)
add_subdirectory(CollisionBox)
add_subdirectory(CollisionResult)
add_subdirectory(CrashData)
add_subdirectory(DamageInfo)
add_subdirectory(DebrisInfo)
add_subdirectory(DecalInfo)
add_subdirectory(Door)
add_subdirectory(EngineStruct)
add_subdirectory(FireInfo)
add_subdirectory(GUI)
add_subdirectory(Game)
add_subdirectory(Gang)
add_subdirectory(GangInfo)
add_subdirectory(Gangs)
add_subdirectory(GarageInfo)
add_subdirectory(GlassInfo)
add_subdirectory(Hud)
add_subdirectory(HudArrow)
add_subdirectory(HudBrief)
add_subdirectory(HudElement)
add_subdirectory(HudMessage)
add_subdirectory(ImpactInfo)
add_subdirectory(JuncIds)
add_subdirectory(LinkedList)
add_subdirectory(MAudio)
add_subdirectory(Medical)
add_subdirectory(Menu)
add_subdirectory(MenuDataBlock)
add_subdirectory(MenuEntry)
add_subdirectory(MenuPage)
add_subdirectory(MenuItemConfig)
add_subdirectory(MenuSlotConfig)
add_subdirectory(Mike)
add_subdirectory(MissionData)
add_subdirectory(MissionManager)
add_subdirectory(ModelIndex)
add_subdirectory(PacketInfo)
add_subdirectory(Particle)
add_subdirectory(Particle1)
add_subdirectory(Particle2)
add_subdirectory(Particles)
add_subdirectory(Passenger)
add_subdirectory(PathNode)
add_subdirectory(Ped)
add_subdirectory(PedManager)
add_subdirectory(PedModel)
add_subdirectory(PedStats)
add_subdirectory(PickupInfo)
add_subdirectory(Player)
add_subdirectory(PlayerData)
add_subdirectory(PlayerSlotSlave)
add_subdirectory(Point2D)
add_subdirectory(Police)
add_subdirectory(PoliceRoadblock)
add_subdirectory(PowerUp)
add_subdirectory(PublicTransport)
add_subdirectory(Radar)
add_subdirectory(RouteInfo)
add_subdirectory(SaveSlotAnimatedValue)
add_subdirectory(SkidmarkInfo)
add_subdirectory(SpawnPoint)
add_subdirectory(Sphere3D)
add_subdirectory(StreamWriter)
add_subdirectory(Tango)
add_subdirectory(TangoMain)
add_subdirectory(Taxi)
add_subdirectory(Teleporter)
add_subdirectory(TextLabel)
add_subdirectory(TextLabelPool)
add_subdirectory(TextureManager)
add_subdirectory(TimeCycle)
add_subdirectory(TrafficCar)
add_subdirectory(TrafficLigthStruct)
add_subdirectory(TransmissionInfo)
add_subdirectory(Turrel)
add_subdirectory(VehiclePool)
add_subdirectory(VertexBuffer)
add_subdirectory(Viewport)
add_subdirectory(Weapon)
add_subdirectory(WeaponInfo)
add_subdirectory(Weapons)
