cmake_minimum_required(VERSION 3.0)
project(MENU LANGUAGES CXX)


# стандарт
set(CMAKE_CXX_STANDARD 98)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -D_M_IX86")

# Основная библиотека MENU 
add_subdirectory(Menu)
# Основная библиотека Player
add_subdirectory(Player)
add_subdirectory(Car)
add_subdirectory(Ambulance)
add_subdirectory(Door)
add_subdirectory(Gangs)
add_subdirectory(MapGm)
add_subdirectory(PublicTransport)
add_subdirectory(MissionManager)
add_subdirectory(Map)
add_subdirectory(AudioSourceParams)
add_subdirectory(MapRelatedStruct)
add_subdirectory(Weapons)


add_subdirectory(Ped)
add_subdirectory(AudioManager)
add_subdirectory(Network)
add_subdirectory(SoundCard)
add_subdirectory(Style)
add_subdirectory(Game)
add_subdirectory(SpriteS1)
add_subdirectory(Turrel)
add_subdirectory(Registry)
add_subdirectory(AIController)
add_subdirectory(CarsPrefabs)
add_subdirectory(GameObject)
add_subdirectory(DMAudio)
add_subdirectory(EventHandler)
add_subdirectory(Replay)
add_subdirectory(CarSystemManager)
add_subdirectory(FileMgr)
add_subdirectory(SpawnPoint)
add_subdirectory(Sprite)
add_subdirectory(Weapon)
add_subdirectory(CrashData)
add_subdirectory(Hud)
add_subdirectory(PlayerData)
add_subdirectory(Police)
add_subdirectory(HudArrow)
add_subdirectory(SaveSlotAnimatedValue)
add_subdirectory(Character)
add_subdirectory(HudBrief)
add_subdirectory(DecalInfo)
add_subdirectory(Object)
add_subdirectory(Text)
add_subdirectory(CameraOrPhysics)
add_subdirectory(CarEngines)
add_subdirectory(DamageInfo)
add_subdirectory(Passenger)
add_subdirectory(PathNode)
add_subdirectory(CarDoor)
add_subdirectory(CollisionBox)
add_subdirectory(Gang)
add_subdirectory(GarageInfo)
add_subdirectory(JuncIds)
add_subdirectory(LinkedList)
add_subdirectory(PedStats)
add_subdirectory(LoadScreen)
add_subdirectory(Taxi)
add_subdirectory(VertexBuffer)
add_subdirectory(ArrowTrace)
add_subdirectory(Checkpoint)
add_subdirectory(Matrix3D)
add_subdirectory(Point2D)
add_subdirectory(TextLabel)
add_subdirectory(BrakeInfo)
add_subdirectory(Camera)
add_subdirectory(Font)
add_subdirectory(Input2)
add_subdirectory(ScriptThread)
add_subdirectory(VehiclePool)
add_subdirectory(General)
add_subdirectory(MAudio)
add_subdirectory(Medical)
add_subdirectory(SpriteS4)
add_subdirectory(TangoMain)
add_subdirectory(TimeCycle)
add_subdirectory(App)
add_subdirectory(CarGenerator)
add_subdirectory(HudMessage)
add_subdirectory(MenuDataBlock)
add_subdirectory(PacketInfo)
add_subdirectory(Particle)
add_subdirectory(PedManager)
add_subdirectory(ScriptVar)
add_subdirectory(TrafficCar)
add_subdirectory(TransmissionInfo)
add_subdirectory(CarModel)
add_subdirectory(FireInfo)
add_subdirectory(Particle1)
add_subdirectory(PedModel)
add_subdirectory(Rect2D)
add_subdirectory(SkidmarkInfo)
add_subdirectory(SpriteS2)
add_subdirectory(WeaponInfo)
add_subdirectory(SpriteInfo)
add_subdirectory(Animation)
add_subdirectory(Collide)
add_subdirectory(ColorRGBA)
add_subdirectory(DebrisInfo)
add_subdirectory(ImpactInfo)
add_subdirectory(Keybord)
add_subdirectory(MenuPage)
add_subdirectory(MenuSlotConfig)
add_subdirectory(Mike)
add_subdirectory(MissionData)
add_subdirectory(ModelIndex)
add_subdirectory(Particle2)
add_subdirectory(PoliceRoadblock)
add_subdirectory(Powerup)
add_subdirectory(Random)
add_subdirectory(ScriptCommand)
add_subdirectory(SpriteS3)
add_subdirectory(Tango)
add_subdirectory(Teleporter)
add_subdirectory(Timing)
add_subdirectory(TrafficLigthStruct)
add_subdirectory(AmbulanceInfo)
add_subdirectory(Controller)
add_subdirectory(EngineStruct)
add_subdirectory(GUI)
add_subdirectory(GangInfo)
add_subdirectory(HudElement)
add_subdirectory(IController)
add_subdirectory(Math)
add_subdirectory(MenuEntry)
add_subdirectory(Particles)
add_subdirectory(PickupInfo)
add_subdirectory(Radar)
add_subdirectory(Renderer)
add_subdirectory(RouteInfo)
add_subdirectory(SoundInfo)
add_subdirectory(Sphere3D)
add_subdirectory(TextureManager)
add_subdirectory(TileAnim)
add_subdirectory(Viewport)
add_subdirectory(Crt)
add_subdirectory(StreamWriter)
add_subdirectory(SpriteSx)