cmake_minimum_required(VERSION 3.0)
project(ENGINE LANGUAGES CXX)


# стандарт
set(CMAKE_CXX_STANDARD 98)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -D_M_IX86")

# пути для include: gta2/, gta2/Game (кросс-инклюды)
include_directories(${CMAKE_CURRENT_LIST_DIR} ${CMAKE_CURRENT_LIST_DIR}/.. ${CMAKE_CURRENT_LIST_DIR}/../Game)

# все поддиректории (классы) сборки Engine (TextureManager берётся из Game, тут дубль)
add_subdirectory(Animation)
add_subdirectory(App)
add_subdirectory(AudioManager)
add_subdirectory(AudioSourceParams)
add_subdirectory(Bink)
add_subdirectory(ColorRGBA)
add_subdirectory(Controller)
add_subdirectory(Crt)
add_subdirectory(DMAudio)
add_subdirectory(Debug)
add_subdirectory(Display)
add_subdirectory(EventHandler)
add_subdirectory(FileMgr)
add_subdirectory(Font)
add_subdirectory(GameObject)
add_subdirectory(General)
add_subdirectory(IController)
add_subdirectory(Input)
add_subdirectory(Input2)
add_subdirectory(KeyBinding)
add_subdirectory(Keybord)
add_subdirectory(LoadScreen)
add_subdirectory(Map)
add_subdirectory(MapGm)
add_subdirectory(MapRelatedStruct)
add_subdirectory(Math)
add_subdirectory(Matrix3D)
add_subdirectory(Movie)
add_subdirectory(Network)
add_subdirectory(Object)
add_subdirectory(Random)
add_subdirectory(Rect2D)
add_subdirectory(Registry)
add_subdirectory(Renderer)
add_subdirectory(Replay)
add_subdirectory(Res)
add_subdirectory(ScriptCommand)
add_subdirectory(ScriptThread)
add_subdirectory(ScriptVar)
add_subdirectory(Sound)
add_subdirectory(SoundCard)
add_subdirectory(SoundInfo)
add_subdirectory(Sprite)
add_subdirectory(SpriteInfo)
add_subdirectory(SpriteS1)
add_subdirectory(SpriteS2)
add_subdirectory(SpriteS3)
add_subdirectory(SpriteS4)
add_subdirectory(SpriteSx)
add_subdirectory(Style)
add_subdirectory(System)
add_subdirectory(Text)
add_subdirectory(TextureManager) 
add_subdirectory(TileAnim)
add_subdirectory(TileNode)
add_subdirectory(Timing)
add_subdirectory(match)
add_subdirectory(ultil)
