cmake_minimum_required(VERSION 3.0)
project(MapRelatedStruct LANGUAGES CXX)

set(CMAKE_CXX_STANDARD 98)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -D_M_IX86")

file(GLOB MAPRELATEDSTRUCT_SOURCE "*.cpp")
file(GLOB MAPRELATEDSTRUCT_HEADERS "*.h")

add_library(${PROJECT_NAME} STATIC ${MAPRELATEDSTRUCT_SOURCE} ${MAPRELATEDSTRUCT_HEADERS})
