
#ifndef __POWERUP_H_
#define __POWERUP_H_

typedef enum PowerUP { /* Повер Апы */
    POWERUP_TYPE_MULTIPLIER = 0,
    POWERUP_TYPE_LIFE = 1,
    POWERUP_TYPE_HEALTH = 2,
    POWERUP_TYPE_ARMOR = 3,
    POWERUP_TYPE_GET_OUTTA_JAIL_FREE_CARD = 4,
    POWERUP_TYPE_COP_BRIBE = 5,
    POWERUP_TYPE_INVULNERABILITY = 6,
    POWERUP_TYPE_DOUBLE_DAMAGE = 7,
    POWERUP_TYPE_FAST_RELOAD = 8,
    POWERUP_TYPE_ELECTROFINGERS = 9,
    POWERUP_TYPE_RESPECT = 10,
    POWERUP_TYPE_INVISIBILITY = 11,
    POWERUP_TYPE_INSTANT_GANG = 12,
    POWERUP_13 = 13,
    POWERUP_14 = 14,
    POWERUP_15 = 15,
    POWERUP_16 = 16,
    POWERUP_17 = 17,
    POWERUP_18 = 18,
}PowerUP;

class PowerUp {
    public:

    // 0x00447370
    int GetNext(void);


};
#endif // !__POWERUP_H_