cmake_minimum_required(VERSION 3.0)
project(Weapons LANGUAGES CXX)

set(CMAKE_CXX_STANDARD 98)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -D_M_IX86")

file(GLOB WEAPONS_SOURCE "*.cpp")
file(GLOB WEAPONS_HEADERS "*.h")

add_library(${PROJECT_NAME} STATIC ${WEAPONS_SOURCE} ${WEAPONS_HEADERS})
