cmake_minimum_required(VERSION 3.0)
project(MissionManager LANGUAGES CXX)

set(CMAKE_CXX_STANDARD 98)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -D_M_IX86")

file(GLOB MISSIONMANAGER_SOURCE "*.cpp")
file(GLOB MISSIONMANAGER_HEADERS "*.h")

file(GLOB PLAYER_HEADERS "../Player/*.h")

add_library(${PROJECT_NAME} STATIC ${MISSIONMANAGER_SOURCE} ${MISSIONMANAGER_HEADERS} ${PLAYER_HEADERS})
